/* Stations 5–13. Each starts on the practice form (smp-01), then shows the same rule on real pages.
   New words are explained in a "Words used here" box before they are used. */
window.STATIONS.push(
/* ================================================================== 5 */
{id: 'owners', n: 5, short: 'Row owners', title: 'Who owns this row?', level: 'Intermediate',
 goal: 'See how the script decides which boxes belong to a row, including tall boxes that started higher up, and why answers taken from those boxes are marked as borrowed.',
 page: {spec: 'smp-01', layers: ['cells'], focus: null},
 beats: [
  {t: 'Meet the practice form',
   x: `<p>From now on every lesson starts on this small made-up form (left). It looks like an AIS table, but it has only 17 rows, and every border sits on a round number, so you can follow the script with your eyes.</p><p>Each tricky situation from the real PDFs appears on it once:</p><ul class="keys"><li><b>A2.2 Height</b>: one question split into three rows (Van, Bus, Mini), and Bus and Mini share one printed answer.</li><li><b>A2.3 Seats</b>: one answer box covering three questions.</li><li><b>A2.0 / A3.0</b>: rows that name the answer columns (Short WB / Long WB, Diesel / Electric).</li><li><b>A3.2 Fuel tank</b>: a very thin empty box squeezed between two answers.</li><li>The signature box at the bottom.</li></ul><p>When a rule makes sense here, we look at the same rule on a real Ashok Leyland page.</p>`,
   x2: `<p class="small muted">The form is made by <code>tools/make_sample.py</code> and read by the real v1.1 script. Everything the lessons show about it comes from that run.</p>`,
   task: {id: 'own-meet', text: 'Click any row of the practice form and read what the row inspector (below the page) says.', on: 'row', test: d => d.spec === 'smp-01'}},
  {t: 'The puzzle: how tall is the Mini?',
   page: {focus: {rows: [7, 8, 9]}, layers: ['cells']},
   words: [['row', 'one horizontal strip of the table. The script numbers them from the top, starting at 0 (row 0 is the title).'], ['cell (box)', 'one rectangle drawn by the printed lines.'], ['merged cell', 'one box stretched over several rows or columns, like "Merge cells" in Excel or Word. Violet on the page.']],
   x: `<p>Look at <b>A2.2 Height</b>. Three bodies: Van, Bus and Mini. The numbers <b>2600</b> and <b>2700</b> are printed <b>once</b>, in boxes two rows tall that cover both Bus and Mini.</p><p>Your eyes say: Mini is 2600 (Short WB) and 2700 (Long WB).</p><p>But the script sees separate boxes. If it only looked at boxes that <i>start</i> in the Mini row, it would find one box, the word "Mini", and no numbers. It would report Mini's height as <b>empty</b>. That is a wrong answer that looks believable, which is the worst kind.</p>`,
   task: {id: 'own-mini', text: 'Click the <b>Mini</b> row on the page. The inspector says which rows it borrows from.', on: 'row', test: d => d.spec === 'smp-01' && d.row === 9}},
  {t: 'The trick: lay a ruler across the row',
   page: {focus: {rows: [7, 8, 9]}, layers: ['cells']},
   words: [['own cell', 'a box whose top edge is inside this row: it "starts" here.'], ['pt', 'the PDF unit of length, about 0.35 mm (see lesson 2).'], ['active cells', 'every box the ruler crosses, own or borrowed, in left-to-right order. This is the list the script works with for that row.']],
   x: `<p>Go through the steps with the buttons. Start with <b>Mini</b>, then try <b>Van</b> and <b>Bus</b> and compare.</p>`,
   viz: ['probe', {spec: 'smp-01', rows: [7, 8, 9], start: 9, names: {7: 'Van', 8: 'Bus', 9: 'Mini'}}],
   x2: `<p>Notice: for Van the ruler crosses the code box "A2.2" and the description "Height (mm)", which <i>started</i> in the Van row, so they are own cells. For Mini, those same two boxes are borrowed, and so are 2600 and 2700.</p>`},
  {t: 'The same steps in the code',
   x: `<p>Now the code should read like the steps you just clicked:</p>`,
   code: {src: 'engine', find: 'def _active_cells(table', n: 7, hl: [4, 5]},
   table: [['Line', 'Step you saw'], ['<code>owners = [c … if c["row"] == row_index]</code>', 'the blue own cells'], ['<code>min(… bbox[1] …)</code>', 'the top of the row (smallest top number)'], ['<code>+ .05</code>', 'move the ruler 0.05 pt down'], ['<code>bbox[1] &lt;= middle &lt; bbox[3]</code>', 'the box starts above the ruler and ends below it, so the ruler crosses it'], ['<code>key=lambda c: c["bbox"][0]</code>', 'sort by left edge: left to right']]},
  {t: 'Borrowed values are labelled as borrowed',
   x: `<p>When an answer comes from a box that started in an earlier row, the script writes <code>inherited_from_merged_cell: true</code> next to it, and <code>source_cell</code> points to the row where the box really starts. For Mini, that is row 8 (Bus).</p><p>Pick an example and a row. Switch on "naive" to see the empty answer a simpler reader would give.</p>`,
   lab: 'merge',
   task: {id: 'own-naive', text: 'In the lab, pick the <b>Mini</b> row and switch on <b>naive</b>.', on: 'lab', test: d => d.id === 'merge' && d.naive && d.row === 9}},
  {t: 'Inside the JSON',
   page: {focus: {rows: [7, 8, 9]}, layers: ['cells']},
   x: `<p>Here is what A2.2 looks like in the output. Tap each value: the box it was read from lights up. The last two point one row up.</p>`,
   viz: ['record', {spec: 'smp-01', code: 'A2.2', rows: [7, 8, 9]}]},
  {t: 'One answer for three questions',
   page: {focus: {rows: [10, 11, 12]}, sel: {row: 11}, layers: ['cells']},
   x: `<p><b>A2.3 Seats</b>: one box says "Refer Annexure S-1" and covers A2.3, A2.3.1 (Front seats) and A2.3.2 (Rear seats). The ruler for each sub-row crosses that box, so <b>each</b> of the three gets the answer, the two lower ones marked borrowed.</p><p>A simple reader would leave Front seats and Rear seats empty. That would be false: the form <i>does</i> answer them, by pointing to the annexure.</p>`,
   x2: `<p>Real case: {{page:t03-01@21,22,23,24|Table 03 B1.8}}, where "Refer Annexure T7 – C" covers B1.8.1–B1.8.3 in exactly this way. A test (<code>test_shared_value_does_not_become_blank</code>) guards it.</p>`},
  {t: 'Now a real page: Table 03 B1.1',
   page: {spec: 't03-01', layers: ['cells'], focus: {rows: [1, 2, 3, 4]}, sel: {row: 4}},
   x: `<p>The real case has the same shape as Van / Bus / Mini: <b>CC / FSD / HSD</b>. The numbers 4925 and 5225 are printed once for FSD and HSD. HSD owns one box (the word "HSD") and borrows four.</p>`,
   task: {id: 'own-hsd', text: 'Click the FSD row, then the HSD row, and compare the inspector lines.', on: 'row', test: d => d.spec === 't03-01' && d.row === 4}},
  {t: 'Why this matters',
   x: `<p>Merged boxes are how these forms say "same for all of these". Getting them wrong gives one of two silent errors:</p><ul class="keys"><li><b>False blanks</b>: a covered row looks unanswered (Mini with no height).</li><li><b>False sharing</b>: an answer spreads to rows it doesn't cover.</li></ul><p>The ruler only shares what the printed box really covers, and it marks every borrowed answer, so a person can always check.</p>`,
   warn: 'The ruler proves where a box is, not what the writer meant. On {{page:t07-01@6,7,8|Table 07}}, the "Variant(s)" answer box also covers the next row, so "Type / Description" gets "Model A8". It is marked borrowed, but the meaning is wrong. Lesson 12 lists this.'},
 ],
 explain: {
  newbie: 'Picture a school timetable where "Maths" is written once in a tall box covering Monday and Tuesday. If you only read the boxes that start on Tuesday, Tuesday looks free. The script avoids that mistake by laying a ruler across each row and writing down every box the ruler touches, even tall boxes that began higher up. It also sticks a note on those answers ("borrowed from the row above") so a person can check.',
  inter: '<code>_active_cells(row)</code> is an interval query: keep every cell whose [top, bottom) contains <code>row_top + 0.05</code>, sorted by x0. The 0.05 pt absorbs tiny float differences between the tops of boxes in one row. Values from cells whose owner row differs are emitted with <code>inherited_from_merged_cell=True</code> and a <code>source_cell</code> pointer: a forward-fill limited to boxes that physically span the row, with provenance.',
  together: 'On the practice form, Mini\'s height is printed once in a box shared with Bus. The script lays a ruler just under the top of the Mini row, collects every box it crosses, and so gives Mini 2600 and 2700, marked as borrowed with a pointer to row 8. Table 03 B1.1 HSD and every "Refer Annexure" box that covers several clauses work the same way. It is the timetable rule: read the tall box for every day it covers, but remember it was written once.'},
 keys: ['A row\'s active cells = every box a ruler laid 0.05 pt under the row\'s top crosses, left to right.', 'Own cells start in the row; borrowed cells started higher up and reach down into it.', 'Borrowed answers get inherited_from_merged_cell = true and source_cell → the row where the box starts.', 'Shared answers ("Refer Annexure…") reach every covered row and never become blanks.'],
 say: '"Each row is read with every box that physically crosses it, so a merged answer reaches all the rows it covers, and those answers are marked as borrowed with a pointer to where they are printed."',
 quiz: [
  {q: 'On the practice form, why does Mini get 2600 and 2700 even though no number box starts in its row?', o: ['The script copies the previous row', 'The 2600/2700 boxes start in the Bus row and reach down across the Mini row, so the ruler for Mini crosses them', 'A regex finds numbers near the word Mini'], a: 1,
   why: ['Not "copy the previous row": a normal one-row box above would NOT be copied. Only boxes that physically reach the row count.', 'Right. The ruler crosses them, so they are active cells of the Mini row.', 'No pattern matching is involved here, only box positions.']},
  {q: 'What does <code>source_cell</code> of Mini\'s 2600 point to?', o: ['Row 9, the Mini row', 'Row 8, the Bus row, where the box starts', 'Nothing'], a: 1,
   why: ['The number is not printed in a box that starts in row 9.', 'Right. A test checks that every source_cell holds exactly the text of its value.', 'Every value has a source; borrowed ones point upward.']},
  {q: 'Why move the ruler 0.05 pt down from the top of the row?', o: ['To be inside every box of this row even if their tops differ slightly, and not touching the row above', 'To make the program faster', 'Because PDF coordinates start at 0.05'], a: 0,
   why: ['Right. Word PDFs often have tops like 109.68 and 109.70 in one row.', 'It has nothing to do with speed.', 'Coordinates start at 0.']},
 ]},

/* ================================================================== 6 */
{id: 'boundary', n: 6, short: 'Boundary', title: 'Where do the answers start?', level: 'Intermediate',
 goal: 'Understand how the script finds the one x position where answers begin (value_x), by letting every coded row vote, and what it does with boxes between the description and that line.',
 page: {spec: 'smp-01', layers: ['roles'], focus: null},
 beats: [
  {t: 'Your eyes vs the script',
   page: {layers: ['roles'], focus: {rows: [1, 2, 3, 4, 5, 6]}},
   words: [['left edge', 'the x where a box starts.'], ['right edge', 'the x where a box ends. A description box from x = 90 to x = 300 has its right edge at 300.']],
   x: `<p>You see three columns: <span style="color:#199e70">■ code</span>, <span style="color:#3987e5">■ description</span>, <span style="color:#d95926">■ answer</span>. The script doesn't see columns. It sees boxes with numbers. To split question from answer it needs one number: <b>the x where answers begin</b>.</p><p>Tap the boxes of A1.1 to see their edges:</p>`,
   viz: ['edges', {spec: 'smp-01', rows: [2]}],
   x2: `<p>On this form the description box ends, and the answer box starts, at <b>x = 300</b>. That number is what the script is looking for. In the code it is called <code>value_x</code>.</p>`},
  {t: 'Why not just say "the third column"?',
   page: {layers: ['cells'], focus: {rows: [5, 6, 7, 8, 9]}},
   x: `<p>Because the column count changes. Look at A2.2: its description box is narrower (it ends at 240) to make room for Van / Bus / Mini. Elsewhere a thin sliver adds another column. The practice form has <b>6</b> columns in the grid although you see 3, and real pages are worse.</p><p>So "the third column" means different things on different rows. A position (x = 300) means the same thing everywhere.</p>`},
  {t: 'Let every row vote',
   words: [['vote', 'each row that starts with a code suggests one number: the right edge of its description box. "I think answers start here."'], ['tally', 'counting how many rows suggested each number.'], ['most common', 'the number suggested by the most rows wins, like a class election. In Python: <code>Counter(…).most_common(1)</code>.']],
   x: `<p>Step through the vote on the practice form. Watch the tally board on the right fill up.</p>`,
   viz: ['votes', {specs: ['smp-01'], spec: 'smp-01'}],
   x2: `<p>13 rows say <b>300</b>. The three A2.2 rows say <b>240</b>, because their description is narrower. 300 wins, so <code>value_x = 300</code>.</p>`},
  {t: 'The vote in the code',
   code: {src: 'engine', find: 'boundaries = []', n: 7, hl: [4, 6]},
   table: [['Line', 'Meaning'], ['<code>for _, code_cell, cells in code_rows</code>', 'only rows whose first box is a code vote'], ['<code>desc = next(… if c["text"])</code>', 'the first filled box right of the code is the description'], ['<code>desc["bbox"][2] &lt; table["bbox"][2] - 5</code>', 'skip a description that runs to the table\'s right side: that row has no answer column'], ['<code>boundaries.append(round(… , 1))</code>', 'drop one vote: the right edge'], ['<code>Counter(boundaries).most_common(1)</code>', 'count the votes and take the winner']]},
  {t: 'Why count votes instead of averaging?',
   x: `<p>Run the vote again with <b>show the average too</b> ticked. The average of the 16 votes is <b>288.8</b>: a number where no box starts or ends.</p>`,
   viz: ['votes', {specs: ['smp-01', 't03-01'], spec: 'smp-01'}],
   x2: `<p>On the practice form the average would still sort boxes correctly, by luck. But every unusual row drags an average further, while the vote only cares which number appears most. Three odd rows or thirty, the winner stays 300. Real forms always have a few odd rows.</p>`,
   analogy: 'Like deciding a class\'s usual bedtime: the most common answer (10 pm) describes the class; the average gets dragged around by one student who says 4 am.'},
  {t: 'What sits between the description and the line',
   page: {focus: {rows: [7, 8, 9]}, sel: {row: 7}, layers: ['roles', 'valuex']},
   words: [['row label', 'a name for one line inside a field, like Van, Bus or Mini. Stored with each value as <code>row_label</code>.']],
   x: `<p>Boxes that start <b>after</b> the description but <b>before</b> value_x become <b>row labels</b>. "Van" starts at 240, before 300, so it is a row label; 2100 starts at 300, so it is an answer. The JSON says <code>{"text": "2100", "row_label": "Van"}</code>.</p>`,
   code: {src: 'engine', find: 'if coded and value_x is not None:', n: 6}},
  {t: 'Move the line yourself',
   x: `<p>Now drag value_x and watch the script's reading change. Try putting it at 240 on the practice form: Van, Bus and Mini turn into answers. That is wrong data that would look perfectly normal in the JSON. The page dropdown also switches the page on the left.</p>`,
   lab: 'boundary',
   task: {id: 'bd-drag', text: 'Drag the line until at least one row is read differently from the real script.', on: 'lab', test: d => d.id === 'boundary' && d.changed > 0}},
  {t: 'On real pages',
   page: {spec: 't02-01', layers: ['roles', 'valuex'], focus: null},
   x: `<p>The same vote on the real forms:</p><ul class="keys"><li>{{page:t02-01|Table 02}}: all 31 coded rows vote <b>288</b>. Unanimous.</li><li>{{page:t03-01@1,2,3,4|Table 03}}: 44 votes for <b>269</b>, 3 for 217.6 and 2 for 213.6 (B1.1 and B1.6.2, whose description is narrowed by CC / FSD / HSD, exactly like A2.2 on the practice form).</li></ul><p>Pick Table 03 in the vote below to watch it.</p>`,
   viz: ['votes', {specs: ['t03-01', 't02-01', 'smp-01'], spec: 't03-01'}]},
  {t: 'No codes, no vote',
   page: {spec: 't07-01', layers: ['roles'], focus: {rows: [24, 25, 26, 27, 28, 29, 30]}},
   x: `<p>{{page:t07-01|Table 07}} prints <b>no codes</b>. No coded rows means no votes, so <code>value_x</code> is empty (<code>None</code>). The script then takes the first filled box as the description and everything right of it as answers.</p><p>That works for "Make and model", but in "Gear ratio" the column headings <i>Gear Ratio | Overall Ratio | …</i> become answers. Lesson 12 lists this.</p>`},
 ],
 explain: {
  newbie: 'Imagine a class trying to agree where the "answers" part of a messy printed form begins. Every student who has a numbered question measures where their question box ends and calls out the number. You write the numbers on the board and pick the one called out most often. A couple of students with odd boxes don\'t change the result. On the practice form 13 rows say 300 and 3 say 240, so the line is drawn at 300. Boxes from 300 onward are answers; small boxes between the question and 300 (Van, Bus, Mini) are row names.',
  inter: '<code>value_x</code> = the mode of <code>description.x1</code> over rows whose first filled cell is a field code (<code>Counter.most_common</code>). The mode is robust to outliers such as rows whose description is narrowed by a row-label column. Cells right of the description with <code>x0 &lt; value_x − 0.2</code> become <code>row_label</code>; the rest become values. Without code rows, <code>value_x</code> is None and the split is weaker.',
  together: 'The script can\'t trust column numbers, because Word adds and removes thin columns from row to row. So every numbered row votes with the x where its description ends, and the most common vote becomes the line where answers start: 300 on the practice form, 288 on Table 02, 269 on Table 03. Boxes between the description and that line are row names (Van / Bus / Mini, CC / FSD / HSD). It is how a class settles on a usual bedtime: by the most common answer, so one odd reply can\'t drag the result.'},
 keys: ['value_x = where answers start = the right edge of description boxes most rows agree on.', 'Each coded row votes once; the most common number wins (not the average).', 'Between the description and value_x: row labels. From value_x on: answers.', 'No coded rows (Table 07) → no value_x → a weaker split.'],
 say: '"Rather than trusting column numbers, every coded row votes with the right edge of its description, and the most common edge becomes the start of the answers. Boxes in between are row labels like CC or FSD."',
 quiz: [
  {q: 'On the practice form, what does the A1.1 row vote?', o: ['90, where its description starts', '300, where its description ends', '580, the right side of the table'], a: 1,
   why: ['That is the left edge of the description. The vote is the right edge.', 'Right: the description "Maker name" ends at 300.', '580 is where the answer box ends.']},
  {q: 'Why do the three A2.2 rows vote 240?', o: ['They are broken', 'Their description box is narrower, to make room for the Van / Bus / Mini column', 'They have no code'], a: 1,
   why: ['Nothing is broken; the layout is different there.', 'Right, and it doesn\'t matter: 13 votes for 300 beat 3 for 240.', 'They do have one: A2.2 (shared by three rows).']},
  {q: 'If value_x were 240 on the practice form, what would go wrong?', o: ['Nothing', 'Van, Bus and Mini would be read as answers instead of row names', 'The script would crash'], a: 1,
   why: ['Try it in the lab: several rows change.', 'Right. Wrong data that looks normal.', 'It would run fine and quietly produce wrong records.']},
 ]},

/* ================================================================== 7 */
{id: 'records', n: 7, short: 'Records', title: 'Rows become records', level: 'Intermediate',
 goal: 'See how the script recognises a clause code, the five questions it asks every row, the difference between a section and a field, and what happens to rows without a code and to thin empty slivers.',
 page: {spec: 'smp-01', layers: ['roles'], focus: null},
 beats: [
  {t: 'What is a record?',
   page: {focus: {rows: [6]}, sel: {row: 6}},
   words: [['record', 'one entry in the output list <code>fields</code>: one question of the form with its code, description and answers.']],
   x: `<p>Every question line of the form becomes one record. A2.1 becomes:</p><pre class="mono small">{"id": "f00006", "field_id": "A2.1", "description": "Length (mm)",
 "values": [{"text": "4200", "column_label": "Short WB"},
            {"text": "4800", "column_label": "Long WB"}], …}</pre><p>To build records the script must first spot which rows <i>start</i> a question. The sign is the code in the first box.</p>`},
  {t: 'Recognising a code',
   words: [['regex (regular expression)', 'a pattern that text must fit, like a stencil. The code pattern says: "maybe one capital letter, then a number, then one or more groups of dot-and-number".']],
   x: `<p>The stencil in plain words:</p>`,
   table: [['Part', 'Means', 'Fits'], ['optional capital letter', 'A, B, D… (a space after it is allowed)', 'A, B , D'], ['a number', 'one or more digits', '1, 22'], ['one or more ".number"', 'at least one dot followed by digits', '.1, .14.4'], ['optional end', 'a trailing dot, or " I." style suffix', '1.1. , D 22.14.4 I.']],
   x2: `<p>Then spaces and the trailing dot are removed: <code>"D 22.14.4 I."</code> → <code>D22.14.4</code>. Because at least one ".number" is required, <code>2026</code> is not a code, but <code>1.65</code> fits. Try it:</p>`,
   lab: 'regex',
   task: {id: 'rec-regex', text: 'Find a text that looks like a number but <b>does</b> fit the code stencil (hint: a gear ratio).', on: 'lab', test: d => d.id === 'regex' && d.code && /^\d+\.\d+$/.test(d.code)}},
  {t: 'Five questions for every row',
   x: `<p>The script walks down the table and asks each row the same five questions, in order. Step through the practice form row by row:</p>`,
   viz: ['decide', {spec: 'smp-01'}],
   x2: `<p>Notice rows 8 and 9 (Bus, Mini): their first box is the code A2.2, but that box belongs to row 7, so they don't start new records. They are added to A2.2. Row 14 has no code at all; it is added to A3.0, and it is also a heading row (lesson 8).</p>`},
  {t: 'Section or field?',
   page: {focus: {rows: [1, 2, 13, 14]}, sel: {row: 1}},
   words: [['section', 'a heading that groups the lines under it, like a chapter title.'], ['field', 'a line that holds an answer.']],
   x: `<p>A record is a <b>section</b> if its code ends in <code>.0</code> (A1.0, A3.0), <b>or</b> if none of its answer boxes has text. Otherwise it is a <b>field</b>.</p><p>On the real {{page:t02-01@8,9,10,11|Table 02}}, A1.7 "Plant/(s) of manufacture" has no .0 but an empty answer, so it is a section, and A1.7.1 and A1.7.2 hang under it.</p>`,
   code: {src: 'engine', find: 'is_section = bool(code and', n: 1}},
  {t: 'Rows without their own code',
   page: {focus: {rows: [7, 8, 9]}, sel: {row: 8}},
   words: [['continuation row', 'a row with no code of its own. Its boxes are kept under the record above it, in <code>continuation_rows</code>.']],
   x: `<p>Nothing is thrown away. The Bus and Mini rows are kept under A2.2 as continuation rows, and because they share A2.2's description box, their answers are also added to A2.2 with their row label (lesson 6).</p><p>Real case: {{page:t4e-01@27,28,29,30,31|Table 4E 1.2.1.13.1 "Engine Power Table"}} has a small table inside the form. Its rows have no codes, so each one becomes a continuation row: <code>["(1)", "1100", "15.5"]</code>, <code>["(2)", "1600", "32.0"]</code>…</p>`},
  {t: 'Thin empty slivers are thrown away',
   page: {focus: {rows: [15, 16, 17]}, sel: {row: 16}, layers: ['roles', 'cells']},
   words: [['spacer (sliver)', 'a very thin box Word leaves behind when borders in different rows don\'t line up. It holds nothing.']],
   x: `<p>In <b>A3.2 Fuel tank</b>, between "60 L" and "NA", there is an empty box only <b>8 pt</b> wide (about 3 mm). Click the row: the inspector says one thin cell was dropped (red on the page).</p><p>The rule (v1.1): drop a box if it is <b>6 pt or narrower</b>, or if it is <b>empty and narrower than 12 pt</b>. Real empty answers are much wider (70+ pt), so they are kept, because "left blank" is information.</p>`,
   code: {src: 'engine', find: 'def _is_spacer(cell', n: 3},
   x2: `<p>Real case: {{page:t06-09@18,19,20|Table 06 E28.4}} had a 7 pt empty sliver. Version 1.0 only dropped boxes up to 6 pt, so it reported an extra empty answer. That was one of the two failed checks; v1.1 fixes it.</p>`},
 ],
 explain: {
  newbie: 'The script reads the table like a teacher marking a register: for every line it asks "is this the signature box? the title? empty? a line without its own number?", and only a line that starts with a question number becomes a new entry. Lines without a number are stapled to the entry above, so nothing gets lost. Tiny empty slivers between boxes are just leftovers from drawing the table and are ignored.',
  inter: 'Per grid row: footer → break; title → continue; empty → continue; no own code cell in a coded table → append to <code>continuation_rows</code> of the previous record (and expand values if the code cell is a merged one); else build a record. <code>field_code()</code> is a full-match regex plus normalisation. <code>kind</code> is a heuristic (.0 or no value text). <code>_is_spacer</code> drops cells ≤ 6 pt, or empty and &lt; 12 pt.',
  together: 'Each grid row goes through the same five questions, and only rows that start with their own clause code become records: A2.1 on the practice form, B1.1 on Table 03. Rows without a code (Bus and Mini, the engine power table in Table 4E) are kept under the record above, and thin empty slivers like the 8 pt one in A3.2 (or the 7 pt one in Table 06 E28.4) are dropped. It is like sorting post: anything with an address goes into its own pigeonhole, notes without an address are clipped to the letter they came with, and scraps of envelope go in the bin.'},
 keys: ['Code stencil: optional capital letter, a number, at least one ".number", optional dot / "I." ending.', 'Five questions per row: signature box → stop; title or empty → skip; no own code → add to previous; else → new record.', 'Section = code ends in .0 or no answer text. It is the script\'s reading, not something the PDF states.', 'Thin slivers (≤ 6 pt, or empty and < 12 pt) are dropped; real blanks stay.'],
 say: '"A row becomes a record when it starts with its own printed clause code. Rows without one are kept under the record above, and only thin empty slivers from the drawing are ignored."',
 quiz: [
  {q: 'Is <code>"2026"</code> a code? Is <code>"1.65"</code>?', o: ['Both are', '2026 is not (no ".number" part); 1.65 fits the stencil', 'Neither'], a: 1,
   why: ['"2026" has no dot, and the stencil needs at least one dot-and-number group.', 'Right. That is why the code must also be the row\'s first filled box: 1.65 in an answer column is just an answer.', '1.65 fits number + ".number".']},
  {q: 'What happens to the Mini row on the practice form?', o: ['It becomes its own record', 'It is kept as a continuation row of A2.2, and its borrowed answers are added to A2.2 with row label "Mini"', 'It is dropped'], a: 1,
   why: ['Its first box is A2.2, but that box belongs to row 7, so it is not a new question.', 'Right.', 'Nothing is dropped.']},
  {q: 'Why is the empty 8 pt box in A3.2 dropped while an empty 80 pt answer box would be kept?', o: ['Random', 'Thin empty slivers are drawing leftovers; a wide empty answer box means "left blank", which is information', 'Empty boxes are always dropped'], a: 1,
   why: ['It is a fixed rule.', 'Right.', 'Real blank answers are kept on purpose.']},
 ]},

/* ================================================================== 8 */
{id: 'labels', n: 8, short: 'Labels', title: 'Names for answer columns', level: 'Advanced',
 goal: 'See how answers get column names (column_label), the three ways the script finds those names, the 80% overlap test, and where the names stop applying.',
 page: {spec: 'smp-01', layers: ['roles'], focus: {rows: [5, 6, 7]}},
 beats: [
  {t: 'Two numbers: which is which?',
   page: {sel: {row: 6}},
   words: [['column label', 'the name of the column an answer sits in, like "Short WB". Stored as <code>column_label</code>.'], ['heading row', 'a row whose boxes name the answer columns below it.']],
   x: `<p>A2.1 Length has two answers: 4200 and 4800. On their own they are useless: which wheelbase is which? The row above, A2.0, says <b>Short WB | Long WB</b>. The script links each answer to the heading above it, so the JSON says <code>4200 → "Short WB"</code>, <code>4800 → "Long WB"</code>.</p>`},
  {t: 'Three ways a heading is found',
   table: [['Kind', 'Rule', 'Practice form', 'Real page'], ['Keyword section', 'a section (.0) with 2+ answer boxes, one mentioning WB, GVW, variant, gear or ratio', 'A2.0 Short WB | Long WB', '{{page:t02-01@27,28|Table 02 A3.0}} GVW 2890 / 3390 kg'], ['Heading row (v1.1)', 'a row with no code, only words over the answer columns, and answers lined up under them in the next rows', 'row 14 Diesel | Electric', '{{page:t06-09@15,16,17,18,19,20|Table 06 E28}} Blower / Low-Cost Heater / AC'], ['Heading field (v1.1)', 'a field whose answers are words, with its own sub-clauses lined up under them', '—', '{{page:t06-04@23,24,25,26|Table 06 E15.3}} Provided Category - 5 / 6']],
   x2: `<p>Headings must be <b>words</b>: "10.0 m", part numbers like "B0CXYZ02", "NA", "Yes" or masked "XXXX" never count as headings.</p>`},
  {t: 'Watch it happen',
   x: `<p>Step through the practice form. Yellow = heading boxes; the yellow tags show the column label each answer gets.</p>`,
   viz: ['headings', {spec: 'smp-01'}]},
  {t: 'Does this answer sit under that heading?',
   words: [['overlap', 'how much two boxes share side by side. 80% overlap means the shared part is more than 80% of the wider box.']],
   x: `<p>An answer gets a heading's name only if they overlap by <b>more than 80%</b> of the wider of the two. "Yellow" in A3.3 is one wide box under both Diesel and Electric: it overlaps each by only 50%, so it gets no label, which is right, because the colour is the same for both.</p>`,
   code: {src: 'engine', find: 'def _header(cell', n: 8, hl: [5]},
   lab: 'overlap',
   task: {id: 'lb-overlap', text: 'In the lab, make the overlap drop below 0.8 so the label disappears.', on: 'lab', test: d => d.id === 'overlap' && d.ratio <= 0.8}},
  {t: 'When headings stop',
   page: {focus: {rows: [13, 14, 15, 16, 17]}, layers: ['roles']},
   words: [['scope', 'the stretch of rows a heading applies to.']],
   x: `<p>Headings must not leak into unrelated rows:</p><ul class="keys"><li>A new <b>.0 section</b> clears them (A3.0 clears Short WB / Long WB).</li><li>A heading row or heading field only covers <b>its own clause family</b>: Diesel | Electric covers A3.x only.</li><li>Exception: a heading row sitting <b>directly above</b> a .0 row survives that .0 (Table 06 puts Blower / Low-Cost Heater / AC right above E28.0).</li></ul><p>Real case: on Table 05, "Description | Capacity" heads the tanks (D7.5.x) and stops before D7.6 Brake Chamber, which has its own heading "Front | Rear | Parking" (see {{page:t05-02|Table 05 page 2}}).</p>`},
  {t: 'On the real pages',
   page: {spec: 't06-09', layers: ['roles'], focus: {rows: [15, 16, 17, 18, 19, 20]}, sel: {row: 20}},
   x: `<p>Table 06 E28.4 Cooling Capacity, after v1.1: <code>NA → Blower</code>, <code>NA → Low-Cost Heater</code>, <code>4 kW → AC</code>. In v1.0 the labels were empty (0/2 label checks). Click rows 18–20 to see each label.</p><p>Also: {{page:t06-04@23,24,25,26|Table 06 E15.3.x}} now carry "Provided Category - 5 / 6", and Table 03's tyre rows carry the brand names APOLLO / CEAT.</p>`},
  {t: 'Still not perfect',
   page: {spec: 't07-01', layers: ['roles'], focus: {rows: [27, 28, 29, 30]}},
   warn: 'On forms without codes ({{page:t07-01@27,28,29|Table 07}}) there is no value_x, so these heading rules don\'t run: "Gear Ratio | Overall Ratio" are stored as answers of "Gear ratio", and the rows below get no labels. The heading rules were checked on these 7 PDFs only; a new layout could fool them (lesson 12).',
   x: `<p>Labels are the most "guessing" part of the script, so they are the part to check first on a new document.</p>`},
 ],
 explain: {
  newbie: 'An answer like "4200" means nothing until you know which column it is in. The script looks for a row that names the columns (like "Short WB | Long WB") and sticks the right name on each answer below it, but only if the answer sits clearly under that name. Names stop applying when a new section starts, so they don\'t get stuck on unrelated lines.',
  inter: 'Header sources: (1) keyword section rows (WB|GVW|variant|gear|ratio); (2) uncoded rows whose value cells are all heading-like and align (>0.8) with a following row\'s values; (3) fields with heading-like values whose next row aligns. Matching: <code>overlap / max(width) &gt; 0.8</code>. Scope: reset at .0 (unless the heading row is directly above it); heading rows scope to the next code\'s family; heading fields to their own sub-clauses.',
  together: 'A value only means something with its column name, so the script finds heading boxes (Short WB | Long WB on the practice form, GVW 2890/3390 kg on Table 02, Blower / Low-Cost Heater / AC on Table 06) and gives each answer the name of the heading it sits under by more than 80%. Names are cleared at the next section or when the clause family ends, so Table 05\'s tank headings don\'t spill onto the brake chambers. It works like column headers in a spreadsheet you freeze at the top: they label everything below, until you start a new sheet.'},
 keys: ['column_label = the heading an answer sits under, matched by > 80% overlap of the wider box.', 'Headings come from keyword sections, heading rows without a code (v1.1), and heading fields (v1.1).', 'Headings must be words, not measurements, part numbers, placeholders or masks.', 'They stop at the next .0 section or at the end of their clause family.'],
 say: '"Each answer is matched to the heading it sits under by more than 80% overlap. Headings come from keyword sections, heading rows and heading fields, and they stop at the next section, so they never leak into unrelated rows."',
 quiz: [
  {q: 'Why does "Yellow" (A3.3) get no column label?', o: ['It is not a number', 'It is one wide box under both Diesel and Electric, overlapping each by only 50%', 'A3.3 is a section'], a: 1,
   why: ['Text values can have labels; "60 L" has one.', 'Right. 50% is not more than 80%.', 'A3.3 is a field with an answer.']},
  {q: 'Why did Table 06 E28.4 have no labels in v1.0?', o: ['The heading words were not read', 'Its heading row has no code and no keyword, and v1.0 only knew keyword sections; also the next .0 row cleared it', 'The values were empty'], a: 1,
   why: ['The words were in the raw table all along.', 'Right. v1.1 adds heading rows and keeps a heading row that sits directly above its .0 row.', 'The values were there.']},
  {q: 'A value spans x 300–400, a heading spans x 300–450. Does it get the label?', o: ['Yes: 100 ÷ 150 ≈ 0.67', 'No: 100 ÷ 150 ≈ 0.67, which is not above 0.8', 'Yes: any overlap is enough'], a: 1,
   why: ['The maths is right, but 0.67 is below 0.8.', 'Right. The ratio uses the wider of the two boxes.', 'Then answers would take the next column\'s name too.']},
 ]},

/* ================================================================== 9 */
{id: 'tree', n: 9, short: 'Tree', title: 'The family tree', level: 'Advanced',
 goal: 'See how each record finds its parent from its code, what happens to rows without codes, how annexure references are picked up, and how a misprinted code behaves.',
 page: {spec: 'smp-01', layers: ['roles'], tab: 'tree'},
 beats: [
  {t: 'A family tree from the codes',
   words: [['parent / child', 'A2.3.1 is a child of A2.3; A2.3 is its parent. Stored as <code>parent_id</code>, the parent record\'s id.'], ['level', 'how deep in the tree: 1 = top.']],
   x: `<p>The codes already say who belongs to whom: A2.3.1 belongs to A2.3, which belongs to A2.0. Step through the practice form:</p>`,
   viz: ['tree', {spec: 'smp-01'}],
   x2: `<p>The rule: chop one piece off the end of the code and look for a record already seen with that code, or with ".0" added. A2.1 → "A2" not seen → "A2.0" seen ✔.</p>`},
  {t: 'The lookup in the code',
   code: {src: 'engine', find: 'def _hierarchy(records', n: 16, hl: [8, 9]},
   x: `<p>The two highlighted lines are the chop-and-look you just watched. Try your own codes:</p>`,
   lab: 'tree',
   task: {id: 'tr-lab', text: 'Run the "misprint" preset and find where E10.2 ends up.', on: 'lab', test: d => d.id === 'tree' && d.preset === 'misprint'}},
  {t: 'Order matters',
   x: `<p>The tree is built in reading order, across all pages. So:</p><ul class="keys"><li>A parent must be printed <b>before</b> its children. That is always true in these forms.</li><li>If a code is printed twice, the <b>later</b> one is used from then on (Table 03 repeats 14 codes).</li><li>Links use record ids (f00008), never codes, because codes can repeat or be missing.</li></ul>`},
  {t: 'Rows without codes (fixed in v1.1)',
   page: {spec: 't07-01', layers: ['roles'], tab: 'tree'},
   x: `<p>{{page:t07-01|Table 07}} prints no codes. A row without a code is placed under the most recent section: "Basic model" goes under "Vehicle data". Good.</p><p>In v1.0 every section also went under the previous section, so they nested: Engine inside Vehicle data, Clutch inside Engine… down to level 28. In v1.1, a section without a code goes <b>next to</b> the previous one (a sibling), so Table 07 is at most 2 levels deep.</p>`},
  {t: 'References to annexures',
   page: {spec: 'smp-01', tab: 'page', layers: ['roles'], focus: {rows: [10, 11, 12]}, sel: {row: 10}},
   words: [['reference', 'a mention of another document or attachment, like "Refer Annexure S-1". Stored in <code>references</code>.']],
   x: `<p>After building the tree, the script searches every record's text for "Annexure", "Annex", "Enclosure" or "Appendix" followed by an identifier. A2.3 and both sub-rows get <code>["Refer Annexure S-1"]</code>.</p><p>v1.1 needs a real identifier (with a digit, like 4K or T7, or a single capital letter like S). v1.0 also picked up phrases like "Annexure with" and "Annexure to".</p>`,
   code: {src: 'engine', find: 'REFERENCE = re.compile', n: 2},
   warn: 'References are copied as text. Nothing opens Annexure T7 – C or links it to the Table 07 pages that contain it.'},
  {t: 'A misprint stays a misprint',
   page: {spec: 't06-04', layers: ['roles'], tab: 'page', focus: {rows: [5, 6, 7, 8, 9]}, sel: {row: 8}},
   x: `<p>Under E13.0, {{page:t06-04@6,7,8,9|Table 06}} prints <b>E10.2</b> and <b>E10.3</b> (copied from E10 on page 3). The script copies codes as printed, so they become children of E10.0 on page 3.</p><p>That is the right call for a copier: silently "fixing" an official declaration is worse than faithfully reporting a typo. A later checking step could flag codes that jump backwards.</p>`},
 ],
 explain: {
  newbie: 'The clause numbers work like family names: A2.3.1 belongs to A2.3, which belongs to A2.0. The script reads every number, chops off the last part, and looks for that shorter number among the ones it has already seen. Lines without a number join the most recent heading. Notes like "Refer Annexure S-1" are collected so you can see where else to look.',
  inter: 'For each coded record, candidates are prefixes from longest to shortest, each tried as-is and with ".0", against a dict of codes seen so far (later duplicates overwrite). Uncoded records attach to the last section; since v1.1 an uncoded section following an uncoded section becomes its sibling. <code>references</code> = de-duplicated REFERENCE matches over description and values.',
  together: 'Parents come from the codes alone: chop the last part and look among codes already seen (with ".0" as an alias), so A2.3.1 → A2.3 and A1.1 → A1.0, and Table 03\'s B1.8.1 → B1.8. Forms without codes, like Table 07, hang lines under the last heading, and since v1.1 headings sit side by side instead of nesting 28 deep. It is like a company directory built only from employee numbers: 4.2.7 reports to 4.2, and a misprinted number puts someone in the wrong department until a person corrects it.'},
 keys: ['Parent = first already-seen code found by chopping the end off, trying each piece as-is and with ".0".', 'Parents come first in the form; repeated codes: the later one wins.', 'No code → under the last section; consecutive uncoded sections are siblings (v1.1).', 'references: "Annexure / Enclosure / Appendix" + an identifier, copied as text.'],
 say: '"The hierarchy comes only from the printed codes: each record links to the nearest earlier prefix, with .0 headings as aliases, using record ids so repeated or missing codes can\'t break it."',
 quiz: [
  {q: 'What is the parent of <code>1.2.1</code> if only <code>1.0</code> has been seen?', o: ['None, because 1.2 is missing', '1.0: the lookup keeps chopping, tries "1", then "1.0"', 'The previous record'], a: 1,
   why: ['It doesn\'t stop at the first missing piece.', 'Right: 1.2, 1.2.0, 1, 1.0 → found.', 'That rule is only for rows without a code.']},
  {q: 'Table 06 prints "E10.2" under E13.0. What does the script do?', o: ['Fixes it to E13.2', 'Links it to E10.0, as printed', 'Drops it'], a: 1,
   why: ['It never rewrites printed text.', 'Right. Faithful to the page, easy to spot in the tree.', 'Nothing is dropped.']},
 ]},

/* ================================================================== 10 */
{id: 'output', n: 10, short: 'Flags', title: 'Warnings and the JSON file', level: 'Advanced',
 goal: 'Know how the signature box is skipped, the three page warnings, what makes a document "needs_review", and the shape of the output file.',
 page: {spec: 'smp-01', layers: ['cells'], focus: null},
 beats: [
  {t: 'The signature box is not data',
   words: [['footer', 'the signature box at the bottom of every page (Manufacturer / Document No / Test agency).']],
   x: `<p>The practice form's signature box is a separate small table. Its first row contains "Manufacturer:" and "Test agency", so the whole table is marked <code>role: "footer"</code> and not turned into records. If such a row appears <i>inside</i> a table, reading stops there.</p><p>v1.1 also recognises a box with "Document No" and "Test agency" when "Manufacturer:" is printed outside it. That removed 6 junk records from {{page:t07-01|Table 07}} pages 1–3.</p>`,
   code: {src: 'engine', find: 'def _is_footer(cells', n: 5}},
  {t: 'Three page warnings',
   table: [['Situation', 'Warning', 'Seen on'], ['No ruled table, but ≥ 40 characters', 'No ruled content table; review the raw text', '{{page:t03-20|Table 03 p.20}}, {{page:t07-04|Table 07 p.4}}'], ['Fewer than 40 characters', 'OCR is required (probably a scan)', 'none of the 7 PDFs'], ['Any picture on the page', 'Images are located, not read', '{{page:t03-01|Table 03 p.1}} (logo), {{page:t11-02|Table 11 p.2}}']],
   x2: `<p>Any warning sets the document's <code>status</code> to <b>needs_review</b>. One logo is enough, which is why Table 03 needs review while Table 05 is complete.</p>`},
  {t: 'A page with nothing to read',
   page: {spec: 't07-06', layers: ['images', 'cells'], focus: null},
   x: `<p>Table 07 page 6: a picture and the signature box. Only the signature table is found, so the page gets two warnings: no content table, and an image that is not read. Nothing is guessed about the picture.</p>`,
   task: {id: 'out-img', text: 'Turn the <b>Images</b> layer off and on.', on: 'layer', test: d => d.layer === 'images'}},
  {t: 'One record, end to end',
   page: {spec: 'smp-01', focus: {rows: [7, 8, 9]}, layers: ['cells']},
   x: `<p>Everything from lessons 5–8 ends up in one record. Tap the values of A2.2:</p>`,
   viz: ['record', {spec: 'smp-01', code: 'A2.2', rows: [7, 8, 9]}],
   task: {id: 'out-json', text: 'Open the <b>JSON</b> tab above the page and click the A2.2 row.', on: 'json', test: d => d.spec === 'smp-01' && !!d.rec}},
  {t: 'The whole file',
   flow: ['schema_version · parser_version', 'document {…}', 'extraction {status, warnings}', 'fields [records]', 'pages [raw_text, tables, images]'],
   x: `<p>Two layers in one file: <b>fields</b> is the script's reading, <b>pages</b> is the evidence (page text, every table cell, picture positions). Anything the reading gets wrong can be checked against the evidence in the same file. Every key is explained with an example in the README.</p><p>Not in the file, on purpose: what pictures show, scanned text, and numbers converted from text ("170 Nm @ 1600 – 2400 rpm" stays as written).</p>`},
 ],
 explain: {
  newbie: 'The output file has two parts: the neat list of questions and answers, and the raw material it was made from (all the text and boxes of each page). The script skips the signature box, and it adds a warning when a page has pictures or almost no text, so a person knows where to look.',
  inter: 'Footer tables (role "footer") keep their cells but produce no records. Page warnings: no content table with ≥ 40 chars → text fallback; < 40 chars → requires_ocr; images → located only. Any warning → <code>extraction.status = "needs_review"</code>. Top-level keys: schema_version, parser_version, document, extraction, fields, pages.',
  together: 'Each JSON file holds the interpretation (fields) next to the evidence (pages), skips signature boxes, and flags pages with pictures, no ruled table or no text, which turns the document to needs_review. On the practice form everything is clean (status complete); Table 03 needs review because of logos. It is like a lab report that gives the results and attaches the raw measurements, with notes on any sample that couldn\'t be measured.'},
 keys: ['Signature boxes are kept as raw cells but never interpreted (v1.1 also catches them without "Manufacturer:").', 'Warnings: no ruled table, OCR needed (< 40 chars), images. Any warning → needs_review.', 'fields = the reading; pages = the evidence. Both in every file.', 'Not extracted: picture content, scanned text, number conversion.'],
 say: '"Every output has the interpreted fields and the raw evidence side by side. Anything we can\'t read is flagged, which marks the document for review."',
 quiz: [
  {q: 'Why is Table 03 "needs_review" while Table 05 is "complete"?', o: ['Table 03 has errors', 'Table 03 has pictures (and a page with no ruled table), which add warnings', 'Table 03 is longer'], a: 1,
   why: ['Its fields came out fine; the status follows warnings.', 'Right.', 'Length plays no part.']},
  {q: 'Where is Table 11\'s heading "Digit 10 in VIN"?', o: ['In fields', 'In pages[1].raw_text: it is printed outside any ruled table', 'Nowhere'], a: 1,
   why: ['Only ruled tables (or the text fallback) make fields.', 'Right.', 'raw_text keeps every page\'s words.']},
 ]},

/* ================================================================== 11 */
{id: 'proof', n: 11, short: 'Proof', title: 'Proving it works', level: 'Expert',
 goal: 'Know how the script was tested: the two piles of PDFs, the freeze, what one check is, what 72/74 means, why v1.1\'s 74/74 is not a new accuracy number, and the 28 tests.',
 page: {spec: 't06-04', layers: ['roles']},
 beats: [
  {t: 'Two piles of PDFs',
   words: [['development set', 'PDFs used while writing and tuning the rules.'], ['holdout (unseen) set', 'PDFs kept aside and used only once, after the rules are fixed, to measure honestly.']],
   table: [['Pile', 'Documents', 'Pages', 'Used for'], ['development', 'Tables 02, 03, 05, 07, 4E', '50', 'writing the rules, tests'], ['holdout', 'Tables 06, 11', '14', 'one scoring run of v1.0']],
   x: `<p>The split is by <b>whole document</b>. Pages of one PDF look alike, so testing on page 9 after tuning on page 8 of the same file would flatter the script.</p>`,
   analogy: 'Like an exam: you practise on past papers, but your grade only counts on a paper you have never seen.'},
  {t: 'Freeze, then score',
   words: [['hash (SHA-256)', 'a fingerprint of a file: change one character and the fingerprint changes completely.']],
   code: {src: 'evaluate', find: 'if not regression and frozen["engine_sha256"] != engine_hash:', n: 2},
   x: `<p>Before the holdout answers were looked at, the fingerprint of <code>engine.py</code> v1.0 was saved. <code>evaluate.py</code> refuses to score the holdout if the engine changed, so nobody can quietly tune on the exam paper.</p>`},
  {t: 'What one check is',
   code: {src: 'evaluate', find: 'def normalized(value)', n: 2},
   x: `<p>A check names a page and a clause (or a table cell) and lists the expected answers, typed from the PDF <b>before</b> the run. Only extra spaces are forgiven: case, units, punctuation, order and blanks must match. <code>["NA","","NA","4 kW"]</code> is not <code>["NA","NA","4 kW"]</code>.</p>`},
  {t: '72 out of 74 (v1.0, unseen)',
   x: `<p>Click any square for the expected and actual values of the v1.0 run.</p>`,
   lab: 'accuracy',
   task: {id: 'pr-fail', text: 'Find one of the two failed checks.', on: 'lab', test: d => d.id === 'accuracy' && d.passed === false}},
  {t: 'And v1.1? 74/74, but read carefully',
   x: `<p>v1.1 fixes both failures, and re-running the same checks gives <b>74/74 values and 2/2 labels</b>. That proves the fixes work on those cases, but it is <b>not</b> a new accuracy number: Tables 06 and 11 were looked at while fixing, so they are no longer an unseen exam. They are now <b>regression</b> checks.</p>`,
   words: [['regression check', 'a test that makes sure something that works keeps working.']],
   code: {src: 'evaluate', find: 'def evaluate(regression=False)', n: 1},
   warn: 'The last unseen measurement is still v1.0\'s 72/74. A real accuracy number for v1.1 needs PDFs nobody has looked at. Say this before anyone asks.'},
  {t: '28 automated tests',
   table: [['File', 'What it guards'], ['test_extraction.py (16)', 'known Table 02 values; B1.1 six variants; shared "Refer Annexure"; hierarchy + footer + GVW labels; every value points to a real cell; code clean-up; blank PDF → requires_ocr; locked / broken PDFs'], ['test_v1_1.py (8)', 'signature box without "Manufacturer:"; sibling sections; heading rows and fields; no false headings; references; and regression checks on Tables 06 and 11'], ['test_app.py (4)', 'upload → review → download → clear; partial failure; bad uploads leave no files; old jobs expire']]},
 ],
 explain: {
  newbie: 'You can\'t mark your own homework on questions you already saw. So two PDFs were locked away, the program was finished and fingerprinted, and only then was it scored on them: 72 of 74 hand-picked answers were right. After fixing the 2 misses, the same test now passes, but that doesn\'t count as a new score, because the "exam" has been seen.',
  inter: 'Document-level split (like GroupKFold), SHA-256 freeze enforced by evaluate.py, expectations written before the run, exact match after whitespace normalisation. 72/74 is a purposive sample, not a population estimate (Wilson ≈ 90.7–99.3% if it were random). v1.1 runs with <code>--regression</code> to a separate report; a new claim needs a fresh holdout.',
  together: 'The script was built on five PDFs and scored once, frozen, on two it had never seen: 72/74 values, 0/2 labels. v1.1 fixed those cases and re-passes them (74/74, 2/2), but that is a regression result, kept in a separate report, not a new accuracy figure. 28 tests guard everything that works today. It is how a driving test works: practice on any road you like, but the test route is only driven once, and a second drive after learning that route doesn\'t count as a new test.'},
 keys: ['Split by document: development (5 PDFs) vs holdout (2 PDFs).', 'v1.0 frozen by hash, then scored once: 72/74 values, 0/2 labels.', 'v1.1 re-passes them (74/74, 2/2) as a regression check, not a new accuracy claim.', '28 tests (16 + 8 + 4) guard current behaviour.'],
 say: '"We split by document, froze v1.0 with a hash and scored 74 hard checks on two unseen PDFs: 72 passed. v1.1 fixes the two misses, but those PDFs are now regression tests; a new accuracy number needs new PDFs."',
 quiz: [
  {q: 'v1.1 passes 74/74 on Tables 06 and 11. Can you tell a client "v1.1 is 100% accurate"?', o: ['Yes', 'No: those PDFs were used while fixing, so it is a regression result, not an unseen measurement', 'Yes, if the version number changed'], a: 1,
   why: ['That would overstate it.', 'Right.', 'A version number doesn\'t make data unseen again.']},
  {q: 'Why split by document rather than by page?', o: ['It is faster', 'Pages of one PDF share layout and quirks, so a page-level split leaks information', 'pytest needs it'], a: 1,
   why: ['Speed is not the reason.', 'Right.', 'Unrelated.']},
 ]},

/* ================================================================== 12 */
{id: 'limits', n: 12, short: 'Limits', title: 'Where it still breaks', level: 'Expert',
 goal: 'Know what v1.1 fixed, what still fails, which new risks v1.1 adds, and how to fix things without fooling yourself.',
 page: {spec: 'smp-01', layers: ['roles'], focus: null},
 beats: [
  {t: 'What v1.1 changed, on the practice form',
   x: `<p>Both versions read the practice form. Only these lines differ:</p>`,
   viz: ['versions'],
   x2: `<p>v1.0 kept the 8 pt sliver as an empty answer and didn't know heading rows without a code. On the real PDFs: Table 06 E28.4 / E29.4 / E29.5 / E29.6 lost their fake blanks, 28 records gained correct labels, Table 07 lost 6 junk records and its 28-level nesting, and 6 junk references disappeared.</p>`},
  {t: 'Still failing: forms without codes',
   page: {spec: 't07-01', layers: ['roles'], focus: {rows: [26, 27, 28, 29, 30]}},
   x: `<p>{{page:t07-01|Table 07}} and {{page:t11-02|Table 11}} print no codes, so there is no vote (value_x) and no heading rules:</p><ul class="keys"><li>"Gear Ratio | Overall Ratio" are stored as answers.</li><li>Table 11's year/month grids are read as rows named after their first box ("YEAR", "2026", "JAN"…). The cells are right; the names are not.</li></ul>`},
  {t: 'Still failing: shape is not meaning',
   page: {spec: 't07-01', layers: ['roles'], focus: {rows: [6, 7, 8, 9]}, sel: {row: 8}},
   x: `<p>The "Variant(s)" answer box covers the next row, so the variant's "Type / Description" gets "Model A8". It is marked <code>inherited</code>, so a reviewer can catch it, but the script can't know the writer meant something else.</p><p>Also still the same: misprinted codes are copied (E10.2 under E13.0), references are text only, text outside tables is only in raw_text, and one logo makes a document "needs_review".</p>`},
  {t: 'Read the Table 11 grids yourself',
   page: {spec: 't11-02', layers: ['roles'], focus: {table: 0}},
   x: `<p>v1.1 removed the empty slivers from these grids, so years and codes now line up. Tick "naive zip" in the lab to see the shift the slivers used to cause.</p>`,
   lab: 'vin',
   task: {id: 'lm-vin', text: 'Decode a year and month in the VIN lab.', on: 'lab', test: d => d.id === 'vin' && d.what === 'decode'}},
  {t: 'New risks that v1.1 adds',
   x: `<ul class="keys"><li><b>Headings on new layouts.</b> The heading rules were checked on these 7 PDFs only. A row of plain words with answers lined up under it could become a heading by mistake. In v1.0 the labels would simply have been empty.</li><li><b>Narrow empty answers.</b> A real empty answer box narrower than 12 pt (4 mm) would now be dropped. None exist in the 7 PDFs.</li><li><b>Signature words inside a table.</b> A content row with both "Document No" and "Test agency" now stops reading that table.</li><li><b>Flattened sub-sections.</b> On forms without codes, real sub-sections become siblings ("Type" under "Suspension" in Table 07).</li><li><b>Record ids.</b> Table 07's ids from f00053 shifted, because the junk records are gone.</li><li><b>Bare "Annexure".</b> A mention with no identifier is no longer listed.</li></ul>`},
  {t: 'How to fix things without fooling yourself',
   flow: ['find a NEW development PDF that shows the problem', 'write a failing test', 'change one rule', 'all tests green', 'bump PARSER_VERSION', '*score on NEW unseen PDFs'],
   x: `<p>v1.1 followed this, except the last step: there were no new unseen PDFs. That is why its 74/74 is reported as a regression result.</p>`,
   pro: 'Showing your known failures, why they happen and how you would fix them is what makes a tech lead trust your numbers.'},
 ],
 explain: {
  newbie: 'v1.1 fixed the problems we measured: fake empty answers from thin slivers, missing column names, junk rows from a signature box, and a family tree that nested too deep. It still struggles with forms that have no question numbers, and it can\'t understand meaning, only layout. The new rules could also make new mistakes on PDFs we haven\'t seen.',
  inter: 'Fixed in 1.1.0: spacer rule (empty &lt; 12 pt), heading rows and heading fields with scoping, footer detection via Document No, sibling uncoded sections, stricter REFERENCE. Open: uncoded tables (no value_x), merged-cell semantics, misprints, unlinked references, raw_text-only text, noisy status. New risks: header false positives on unseen layouts, narrow real blanks, footer keyword collisions, id shifts.',
  together: 'v1.1 fixed every failure the v1.0 holdout exposed (the 7 pt sliver, the missing Blower / Category labels) plus Table 07\'s junk records and deep nesting, which the practice form shows side by side. What remains is the layout-versus-meaning gap: forms without codes like Table 07 and 11, merged boxes that mean "same value" only sometimes, and misprints. The new heading rules may also misfire on unseen layouts. Like a car after a recall fix: the reported faults are fixed and tested, but it needs fresh miles on new roads before anyone can say how reliable it is.'},
 keys: ['Fixed in v1.1: slivers, heading rows/fields, Document-No footers, sibling sections, stricter references.', 'Still failing: forms without codes, layout vs meaning, misprints, unlinked references, noisy status.', 'New risks: heading false positives, narrow real blanks, footer words in tables, Table 07 id shift.', 'Fix on new development PDFs, measure on new unseen PDFs.'],
 say: '"v1.1 fixes the measured failures; what\'s left is mostly forms without clause codes and the gap between layout and meaning. Its new heading rules need fresh unseen PDFs before I quote an accuracy number."',
 quiz: [
  {q: 'Which root cause explained Table 06 E28.4 in v1.0?', o: ['OCR misread "NA"', 'A 7 pt empty sliver passed the ≤ 6 pt filter and became an answer', 'A missing heading row'], a: 1,
   why: ['No OCR is involved.', 'Right; v1.1 drops empty boxes under 12 pt.', 'That explains the missing labels, not the extra blank.']},
  {q: 'Why does Table 07 still store "Gear Ratio | Overall Ratio" as answers?', o: ['A bug in the regex', 'Table 07 has no codes, so there is no value_x and the heading rules don\'t run', 'The words are pictures'], a: 1,
   why: ['The regex is not involved here.', 'Right.', 'They are real text.']},
 ]},

/* ================================================================== 13 */
{id: 'mastery', n: 13, short: 'Own it', title: 'Own it', level: 'Mastery',
 goal: 'Explain the project at three depths, compare it with the earlier OCR + AI pipeline, extend it safely, and lay out a credible roadmap.',
 page: {spec: 't02-01', layers: ['roles']},
 beats: [
  {t: 'Three depths of the same story',
   table: [['Time', 'Say this'], ['10 s', 'It turns AIS-007 spec PDFs into JSON where every value points back to its box. Local, CPU-only, same input → same output.'], ['1 min', '+ It rebuilds tables from the printed lines, uses clause codes as keys, handles merged boxes with a borrowed flag and flags what it can\'t read. v1.0 scored 72/74 on two unseen PDFs; v1.1 fixed both misses.'], ['5 min', '+ the ruler for active cells, the value_x vote, headings by 80% overlap, the tree from codes, the freeze, the regression rule, and the remaining limits.']],
   pro: 'Always end with a limit and a next step.'},
  {t: 'Why not OCR + an AI model?',
   table: [['', 'This project', 'Earlier [[lexbolt|Lexbolt]] pipeline'], ['Reads', 'real text + printed lines', 'page images via [[paddle|PaddleOCR-VL]] on [[vllm|vLLM]]'], ['Hardware', 'any CPU', 'GPU'], ['Text errors', 'none (exact characters)', 'possible OCR errors'], ['Rows without a code', 'kept as continuation rows', '[[nilclause|NIL clause]] → an AI model guesses'], ['Scanned PDFs', 'flagged, not read', 'read'], ['Same input → same output', 'always', 'not guaranteed']],
   x2: `<p>For Word-exported PDFs, positions are cheaper, exact and checkable. OCR or a vision model earns its place for scanned pages, as a separate, clearly marked path.</p>`},
  {t: 'Extending it safely',
   x: `<ol><li>Get a PDF that shows the new layout; add it to <code>pdfs/development/</code> and the manifest.</li><li>Write a failing test with the answers from the page.</li><li>Change one rule in <code>engine.py</code>; keep it explainable with positions.</li><li>Run <code>pytest</code>: all old tests must stay green.</li><li>Run <code>evaluate.py --regression</code> to re-check Tables 06 and 11.</li><li>Bump <code>PARSER_VERSION</code>; measure on new unseen PDFs before quoting a number.</li></ol>`,
   code: {src: 'engine', find: 'PARSER_VERSION = "1.1.0"', n: 1}},
  {t: 'From laptop tool to service',
   table: [['Today', 'For a shared deployment'], ['jobs in memory', 'database + durable queue'], ['one worker thread', 'worker processes, scaled by load'], ['127.0.0.1, no login', 'login, HTTPS, audit log'], ['scans flagged', 'optional OCR path, clearly marked'], ['labels by rules checked on 7 PDFs', 'measured on a new unseen set']]},
  {t: 'Your kit for the room',
   x: `<ul class="keys"><li><a href="#/defense">🎙 Defense room</a>: a client, a tech lead and an interviewer ask hard questions.</li><li><a href="#/cheat">⚡ Cheat sheet</a>: numbers, one-liners and flashcards.</li><li><a href="#/code">📜 Code reader</a>: every function with a plain-English note.</li><li><a href="#/atlas">🗂 Page atlas</a>: every page, including the practice form.</li></ul>`},
 ],
 explain: {
  newbie: 'You now know the whole path: lines become boxes, boxes in a row are collected with a ruler, a vote finds where answers start, codes make records and a family tree, headings name the answer columns, and everything unclear is flagged. You also know how it was tested and where it is still weak, which is what people will ask about.',
  inter: 'A rule-based, provenance-preserving extractor: interval queries for active cells, mode-based column boundary, header matching by overlap ratio with scoping, prefix-based hierarchy, explicit warnings; evaluated with a document-level holdout and hash freeze; v1.1 changes covered by regression tests.',
  together: 'Jags AL Data Extracter copies Ashok Leyland\'s AIS forms into JSON by reading positions, not by guessing: the practice form showed each rule in isolation, and the real pages showed it at scale. You can explain the ruler, the vote, the headings and the tree, quote v1.0\'s 72/74 honestly, say why v1.1\'s 74/74 is a regression result, and name the remaining limits. That is owning a project: knowing what it does, how you know, and where it stops.'},
 keys: ['Have a 10 s, 1 min and 5 min version, each ending with a limit and a next step.', 'Positions beat OCR/AI for Word-exported PDFs; OCR is a marked path for scans.', 'Extend: new dev PDF → failing test → one rule → green → regression → new unseen set.', 'Production: database + queue, login, OCR path, fresh evaluation.'],
 say: '"For Word-exported spec sheets, a position-based parser is exact, cheap and checkable. I know its measured failures, what v1.1 fixed, and what needs new data before I quote a number."',
 quiz: [
  {q: 'A client says "just use an AI model, it reads tables". Best answer?', o: ['Agree and switch', 'For these PDFs our parser is exact, repeatable and traceable at no per-page cost; an AI model may paraphrase or guess. For scans we would add OCR as a marked path', 'AI models can\'t read PDFs'], a: 1,
   why: ['That throws away exactness and traceability.', 'Right.', 'Over-claiming hurts credibility.']},
  {q: 'What must happen before you quote a new accuracy number for v1.1?', o: ['Re-run evaluate.py --regression', 'Score v1.1 on PDFs not used to build it', 'Run pytest'], a: 1,
   why: ['That is a regression check.', 'Right.', 'pytest guards known behaviour.']},
 ]}
);
