/* Stations 0–4 (5–13 are in journey2.js). Each beat drives the page on the left (page:{spec, layers, focus, sel, tab}). */
window.STATIONS = [
/* ================================================================== 0 */
{id: 'start', n: 0, short: 'Start', title: 'Start here', level: 'Orientation',
 goal: 'Know what SpecExtract is, the whole pipeline in one line, and the four truths the design rests on.',
 page: {spec: 't02-01', layers: []},
 beats: [
  {t: 'What you built, in one sentence',
   x: `<p><b>Jags AL Data Extracter</b> reads Ashok Leyland's [[ais007|AIS-007]] specification PDFs and writes JSON in which <b>every value points back to the exact cell it came from</b>. It runs locally on a CPU, with no API keys or models.</p><p>On the left is <b>Table 02</b>: one page, 31 fields. It is the engine we'll take apart, one station at a time.</p>`,
   tiles: [['7', 'PDFs supplied'], ['64', 'pages'], ['2,121', 'records extracted (v1.1)'], ['28/28', 'tests pass'], ['72/74', 'checks on unseen PDFs (v1.0)'], ['0', 'API keys or GPUs']]},
  {t: 'The whole story in one line',
   x: `<p>This is the core diagram. Every station opens one box of it, and the metro line at the top tracks where you are.</p>`,
   flow: ['PDF bytes', '[[pdfplumber]]: chars + lines', '[[findtables|find_tables]] → cells', '[[active|active cells]] per row', 'row → [[record]]', '[[hierarchy|parent tree]]', 'JSON + page flags', '[[holdout]] evaluation'],
   x2: `<p>Around it sits a small <b>[[fastapi|FastAPI]] app</b> (upload → queue → review → download) and an <b>evaluation</b> that proves the parser on PDFs it never saw during tuning.</p>`,
   analogy: 'It is a feature pipeline with no learned model: geometry in, structured records out, and every output row keeps a foreign key (source_cell) back to its raw input.'},
  {t: 'The four truths everything rests on',
   x: `<ol><li><b>A [[pdf]] has no tables.</b> It only has ink at coordinates plus drawn lines. Every table is <i>reconstructed</i>.</li><li><b>Geometry is the evidence.</b> Each value keeps its cell ([[source_cell]]) and box ([[bbox]]).</li><li><b>Never invent.</b> Copy text verbatim (units, <code>NA</code>, <code>--</code>, blanks). Flag what can't be read instead of guessing.</li><li><b>A score only counts on unseen data.</b> Freeze the parser, then test on the [[holdout]].</li></ol>`,
   pro: 'Almost every design choice you will be asked about ("why no OCR?", "why not convert numbers?", "why is 97.3% not the accuracy?") follows from one of these four truths. Name the truth, then give the detail.'},
  {t: 'Touch the page',
   page: {layers: ['roles']},
   x: `<p>The colours show what the engine decided for each cell: <span style="color:#199e70">■ code</span>, <span style="color:#3987e5">■ description</span>, <span style="color:#d95926">■ value</span>, <span style="color:#8a96a3">■ skipped</span>.</p><p>Click any row. The <b>row inspector</b> under the page shows the engine's decision for that row: the record it made, its values, and why.</p>`,
   task: {id: 'start-click', text: 'Click any row of the table on the page.', on: 'row'}},
  {t: 'How to use this app',
   x: `<ul class="keys"><li><b>← →</b> (keyboard) or the buttons move between beats. Each beat is one idea.</li><li><b>Layer chips</b> above the page switch overlays on and off: words, lines, cells, roles, the value boundary.</li><li><b>Tree / JSON</b> tabs show the same selection as a hierarchy or as the actual output record.</li><li><b>Tasks</b> tick themselves when you do the thing. <b>Checkpoints</b> end each station.</li><li>Dotted words have hover definitions. <b>▶ Show me</b> buttons set the page up for you.</li></ul>`,
   x2: `<p>From lesson 5 on, each lesson first runs the rule on a small {{page:smp-01|practice form}} made for this course, then on the real pages. Any 📄 link in a lesson puts that page on the left; <b>↩ Back to lesson page</b> brings the lesson's page back.</p>`,
   warn: 'Code and numbers here come straight from your files. The page traces are produced by re-running the real engine and are checked record by record against its output. Regulatory background (AIS, CMVR, vehicle categories) is general knowledge; confirm specifics with your homologation colleagues.'},
 ],
 explain: {newbie: 'Think of the PDF as a photo of a filled-in form, except the computer can see every printed letter and line with its exact position. The program looks at where the lines are, works out the boxes, decides which box is a question and which is an answer, and writes it all into a neat list (JSON). Every answer keeps a note of the box it came from, so anyone can check it.', inter: 'A deterministic pipeline: pdfplumber gives chars and ruling lines; find_tables() rebuilds cells; rule-based passes turn rows into records with provenance (source_cell, bbox); a hierarchy pass links parents; evaluation on held-out documents checks it. No model, no network, same input → same output.', together: 'Jags AL Data Extracter treats each Ashok Leyland AIS form like a filled-in paper form: it finds the boxes from the printed lines, reads question and answer boxes by their position, and writes a list where every answer points back to its box. It is like a careful clerk copying a form into a spreadsheet and writing the page and box number next to every entry, so a checker can verify anything in seconds.'},
 keys: ['SpecExtract = native-text PDF tables → traceable JSON, CPU-only, deterministic.', 'Pipeline: bytes → chars/lines → cells → active cells → records → tree → JSON → evaluation.', 'Four truths: no tables in a PDF; geometry is evidence; never invent; score on unseen data.'],
 say: '"It\'s a deterministic extractor: it rebuilds each table from the PDF\'s ruling lines, keeps every value tied to its source cell, and flags anything it can\'t read instead of guessing."',
 quiz: [
  {q: 'Why does every value in the output carry a <code>source_cell</code>?', o: ['To make the JSON bigger so it looks complete', 'So any value can be traced to the exact cell on the page and checked by a reviewer', 'Because pdfplumber requires it'], a: 1,
   why: ['Size is not the goal. Every key in the output has a job.', 'Traceability is truth #2: geometry is the evidence. A reviewer, or a test, can jump from a value to its cell.', 'pdfplumber knows nothing about your output format. The engine chose to keep this link.']},
  {q: 'Which statement matches truth #3, "never invent"?', o: ['Convert "10 degs" to the number 10 so it is easier to use', 'Leave an unreadable scanned page empty and say nothing', 'Keep "NA", "--" and blanks exactly as printed, and flag pages that need OCR'], a: 2,
   why: ['Converting drops the unit and makes an interpretation. Doing that belongs downstream, where the rules are explicit.', 'Staying silent is also a kind of invention: it implies there was nothing there. The engine adds a warning instead.', 'Correct. Placeholders are data, and unreadable content is reported, never guessed.']},
 ]},

/* ================================================================== 1 */
{id: 'paper', n: 1, short: 'Paperwork', title: 'The paperwork', level: 'Beginner',
 goal: 'Understand what these forms are, who writes and signs them, and why exact values matter.',
 page: {spec: 't02-01', layers: []},
 beats: [
  {t: 'Why these PDFs exist',
   x: `<p>Before a vehicle model can be sold in India it needs [[typeapproval|type approval]]. The manufacturer <b>declares</b> its specifications, and an accredited [[testagency|test agency]] tests the vehicle and certifies it.</p>`,
   flow: ['Ashok Leyland declares specs', '*AIS-007 tables (these PDFs)', 'test agency checks + signs', 'approval ([[tac|TAC]])', 'vehicle on sale'],
   x2: `<p>[[ais007|AIS-007]] defines <i>what</i> must be declared, as numbered tables: Part A General, B Vehicle overall, D Brakes, E Electrical and so on. The signature block at the bottom of every page is where both sides sign.</p>`,
   show: [{label: 'Show the signature block', page: {focus: {table: 1}, layers: ['cells']}}],
   warn: 'This is general regulatory background, not from your files. The files themselves only say "Table N of AIS-007 (Revision 5)", "as per Rule 122 of CMVR", and so on.'},
  {t: 'Anatomy of one table',
   page: {layers: ['roles'], focus: {rows: [0, 1, 2, 3, 4, 5, 6, 7, 8]}},
   x: `<p>Every AIS table has the same skeleton:</p><ul class="keys"><li><b>Title row</b>: "Table 2 of AIS-007 (Revision 5) … PART A – GENERAL".</li><li><b>Code column</b>: printed [[fieldcode|field codes]] such as A1.0, A1.1 and A1.6.1. <code>.0</code> marks a section heading.</li><li><b>Description column</b>: what is being declared.</li><li><b>Value column(s)</b>: the declaration itself. There are several columns when variants differ.</li></ul>`,
   pro: 'The code is the stable key. "A1.6" means "Name of model and variants" in every manufacturer\'s Table 2. That is why the engine builds everything around codes.'},
  {t: 'The seven documents you were given',
   table: [['Document', 'What it declares', 'Pages', 'Set'], ['{{page:t02-01|Table 02}} · Part A', 'Manufacturer, vehicle type, performance', '1', '[[dev|dev]]'], ['{{page:t03-01|Table 03}} · Part B', 'Dimensions, weights, tyres, steering, safety fittings', '20', 'dev'], ['{{page:t4e-01|Table 4E}}', 'BS VI engine & emission system (GVW ≤ 3500 kg)', '15', 'dev'], ['{{page:t05-01|Table 05}} · Part D', 'Brakes', '8', 'dev'], ['{{page:t07-01|Table 07}}', 'Brief spec summary + Annexure T7-A masses', '6', 'dev'], ['{{page:t06-04|Table 06}} · Part E', 'Electrical: lamps, EMC, AC/ventilation, VAS', '12', '[[holdout|holdout]]'], ['{{page:t11-02|Table 11}}', 'Chassis-number location + VIN date codes', '2', 'holdout']],
   x2: `<p>The vehicle in all seven is the <b>Model A9 / A8</b>, an [[n1|N1]] light goods vehicle. Browse every page in the <a href="#/atlas">Page atlas</a>.</p>`},
  {t: 'Variants: why one field has many values',
   page: {spec: 't03-01', layers: ['roles'], focus: {rows: [1, 2, 3, 4, 5, 6, 7, 8]}},
   x: `<p>One form covers several [[variant|variants]], so values fan out:</p><ul class="keys"><li>by [[wb|wheelbase]]: <b>2490 WB</b> vs <b>2640 WB</b> (columns)</li><li>by body: <b>[[ccfsd|CC / FSD / HSD]]</b> (row labels)</li><li>by [[gvw|GVW]]: 2890 kg vs 3390 kg ({{page:t02-01@27,28|Table 02, A3.0}})</li></ul><p>So "Overall Length" (B1.1) has six values. A value is only meaningful <b>together with its variant labels</b>.</p>`,
   task: {id: 'paper-b11', text: 'On Table 03, click the B1.1 row with the CC / 2490 WB value 4750.', on: 'row', test: d => d.spec === 't03-01' && d.row === 2}},
  {t: 'Placeholders are data',
   page: {spec: 't02-01', layers: ['roles'], focus: {rows: [12, 13, 14, 15, 16]}},
   x: `<p>Look at A1.8 (importer): <code>NA</code>, then <code>--</code> four times. On other pages you'll meet <code>-</code>, blanks, and masked text like <code>044-XXXXXXXX</code>, because these copies are anonymised.</p><p>They mean different things. "Not applicable", "not filled in" and "left empty" are three different statements to an auditor, so the engine copies them <b>exactly</b>.</p>`,
   analogy: 'Like missing-value types in a dataset: NaN, the string "N/A" and 0 are different signals. Collapsing them destroys information you can\'t get back.'},
  {t: 'Read one real value',
   page: {focus: {rows: [22, 23, 24, 25, 26]}, sel: {row: 24}},
   x: `<p>A2.2: "Category of vehicle as per IS 14272:2011" → <b>N1</b>. That one cell decides which rules apply to the whole vehicle: N1 is a goods vehicle up to 3.5 t.</p><p>The row inspector shows the record the engine made: code, description, one value, and its parent (A2.0).</p>`,
   task: {id: 'paper-tree', text: 'Open the <b>Tree</b> tab above the page and find A2.2 under A2.0.', on: 'tab', test: d => d.tab === 'tree'}},
 ],
 explain: {newbie: "These PDFs are the official spec sheets a vehicle maker sends for approval. Each line has a number (like A1.6) that is the same in every company's form, so the number is the best name for that line. One line can have several answers because one form covers several versions of the truck.", inter: 'The clause code is the natural primary key; values are multi-valued and keyed by variant dimensions (wheelbase columns, body-type rows, GVW). Placeholders (NA, --, blank) are distinct states and must be preserved, not normalised to null.', together: "An AIS table is a standard questionnaire where the clause code (A2.2, B1.1) is the question's permanent ID and the answers can split by variant: Overall Length has six answers because of three bodies times two wheelbases. Like a school report card where 'Maths' is the same subject code for every student, but each term has its own mark, the code identifies the question and the variant labels identify which answer you are looking at."},
 keys: ['These PDFs are type-approval declarations: legal statements that a test agency signs.', 'AIS-007 fixes the codes (A1.6, B1.1 …), so the code is the stable key.', 'Values fan out by variant (WB, body, GVW), so labels are part of a value\'s meaning.', 'NA, --, -, blanks and masks are different statements and must survive verbatim.'],
 say: '"These are AIS-007 type-approval declarations. The printed clause codes are the stable keys, and the value only means something together with its variant, like 2490 WB or FSD."',
 quiz: [
  {q: 'Why would converting <code>--</code> and <code>NA</code> both into <code>null</code> be a bad idea?', o: ['It would make the JSON invalid', 'They can mean different things (not filled vs not applicable), and an auditor may care which', 'pdfplumber cannot read dashes'], a: 1,
   why: ['null is perfectly valid JSON. The problem is meaning, not syntax.', 'Correct. The extractor is a copier, not an interpreter. Collapsing placeholders loses the declared intent.', 'It reads them fine. The question is whether to rewrite them.']},
  {q: 'B1.1 "Overall Length" has six values. What is needed to use one correctly?', o: ['Only the number', 'The number plus its variant labels (e.g. FSD, 2640 WB)', 'The page number'], a: 1,
   why: ['4925 alone is ambiguous. It is the length of two different bodies on one wheelbase.', 'Correct. That is why values carry row_label and column_label.', 'The page helps trace the value, but it does not tell you which variant it belongs to.']},
 ]},

/* ================================================================== 2 */
{id: 'inside', n: 2, short: 'Inside a PDF', title: 'Inside a PDF', level: 'Beginner',
 goal: 'See the page the way pdfplumber sees it: words with boxes, separate lines, and no table object.',
 page: {spec: 't02-01', layers: ['ink']},
 beats: [
  {t: 'Zoom in: there is no table here',
   page: {layers: ['ink'], focus: {rows: [6, 7, 8, 9, 10]}},
   x: `<p>To pdfplumber this page is <b>2,336 [[glyph|characters]]</b>. Grouped by closeness they make <b>384 words</b>, and each grey box on the left is one of them, with a [[bbox]].</p><p>Nothing in the file says "this word is in row 7, column 3". The PDF only says "draw these letters here".</p>`,
   analogy: 'Think of object detection output: a list of boxes with labels, and no relations between them. Recovering the structure (rows, columns, ownership) is your job, done in post-processing.'},
  {t: 'The lines are separate drawings',
   page: {layers: ['rules'], focus: null},
   x: `<p>The table borders are also just drawings: <b>812 horizontal and 830 vertical [[edge|edges]]</b> on this page. Word draws each cell border as its own small line or rectangle side, which is why there are so many.</p><p>Turn the <b>Ruling lines</b> layer on and off. Without these lines, no table would ever be found.</p>`,
   task: {id: 'inside-rules', text: 'Switch the <b>Ruling lines</b> layer off and back on.', on: 'layer', test: d => d.layer === 'rules'}},
  {t: 'Native text vs a scanned page',
   x: `<p>These PDFs were exported from Word, so the text is [[native|native]]: real characters you can select. A [[scanned]] page is only a photograph, with zero characters.</p><p>Look at {{page:t07-06|Table 07 page 6}}. It holds a logo image and the signature footer, and nothing else to read.</p>`,
   show: [{label: 'Show Table 07 page 6', page: {spec: 't07-06', layers: ['images', 'cells'], focus: null}}, {label: 'Back to Table 02', page: {spec: 't02-01', layers: ['ink'], focus: null}}],
   pro: 'Native text is why SpecExtract needs no [[ocr|OCR]] and why its text is exact: it copies the characters Word wrote, so there are no recognition errors. The price is that a scanned PDF yields nothing, and the engine says so.'},
  {t: 'Coordinates: the language of the engine',
   page: {spec: 't02-01', layers: ['cells'], focus: {rows: [27, 28]}},
   words: [['pt (point)', 'the PDF unit of length: 1/72 of an inch, about 0.35 mm. An A4 page is 595 pt wide and 842 pt tall.'], ['x', 'how far from the <b>left</b> side of the page, in pt.'], ['y (top)', 'how far down from the <b>top</b> of the page, in pt. It grows as you go down.'], ['bbox', 'the four numbers that pin a box to the page: [left x, top y, right x, bottom y].']],
   x: `<p>Every box on the page is described by four numbers. Click the boxes of the A3.1 row below: the small picture shows where the box is on the whole page, the big one gives its edges in pt.</p>`,
   viz: ['coords', {spec: 't02-01', rows: [28], pick: '28,4'}],
   x2: `<p>So "8.5 degs" sits from x = 414 to x = 567. Every later rule is a comparison of numbers like these: "does this box start right of the description?", "is this box thinner than 6 pt?". The script stores them, rounded to 3 decimals, with every value:</p>`,
   code: {src: 'engine', find: 'def bbox(box)', n: 2}},
  {t: 'Two readings of the same page',
   x: `<p>The engine reads each page twice:</p><ol><li><b>Plain text</b> with [[extract_text]], grouping characters with tolerances x = 2 pt and y = 3 pt. It is stored as <code>raw_text</code>, a readable fallback for every page.</li><li><b>Tables</b>, rebuilt from lines (next stations).</li></ol>`,
   code: {src: 'engine', find: 'raw_text = page.extract_text', n: 3, hl: [0, 2]},
   why: '',
   pro: 'Keeping raw_text means that even when table interpretation fails, nothing is lost: a reviewer can still read the page\'s words in the Text tab of the review UI.'},
 ],
 explain: {newbie: "A PDF doesn't know it contains a table. It only says 'draw letter A here, draw a line there'. The program has to rebuild the table from those lines, like rebuilding a grid from the chalk lines on a floor.", inter: 'pdfplumber exposes chars (with x0/top/x1/bottom) and edges (line segments). Tables are inferred from edge intersections. Native-text PDFs give exact strings, so no OCR error model is needed; scans produce no chars and are flagged.', together: 'To the script, a page is only letters and lines, each with x and y numbers measured in points from the top-left corner. Because these Ashok Leyland PDFs were exported from Word, the letters are real text, so they are copied exactly, and the table is rebuilt from the printed lines. It is like finding your way through a city with only a list of street coordinates: no map is given, but the coordinates are enough to redraw one.'},
 keys: ['A PDF is glyphs + lines at coordinates. Tables do not exist until you rebuild them.', 'Ruling lines are the raw material for the table grid.', 'Native text means exact characters and no OCR. A scanned page has none, so it gets flagged.', 'Coordinates are PDF points from the top-left, and every value keeps its bbox.'],
 say: '"There\'s no table object inside a PDF, only positioned characters and ruling lines. We rebuild the grid from the lines, and because these are native-text exports, the text is exact with no OCR."',
 quiz: [
  {q: 'A supplier sends a scanned PDF of Table 05. What does SpecExtract do?', o: ['Runs OCR automatically', 'Finds under 40 characters per page, marks the pages requires_ocr, and sets status needs_review', 'Crashes'], a: 1,
   why: ['There is no OCR in this project, by design.', 'Correct. It reports the problem honestly instead of guessing.', 'It handles this gracefully. A blank PDF is even covered by a test (test_no_text_is_flagged).']},
  {q: 'Why is the table found from ruling lines and not from text alignment?', o: ['Lines give exact cell borders, including merged cells. Aligned text can\'t show where a merged cell ends.', 'Text has no coordinates', 'Lines are faster to download'], a: 0,
   why: ['Correct. Borders show spans; whitespace is ambiguous.', 'Text has coordinates too. What it lacks is the cell boundaries.', 'Everything is already local. The reason is accuracy, not speed.']},
 ]},

/* ================================================================== 3 */
{id: 'door', n: 3, short: 'Front door', title: 'The front door', level: 'Intermediate',
 goal: 'Explain the upload → queue → review → download flow in app.py, its limits, and why it is built that way.',
 page: {spec: 't02-01', layers: []},
 beats: [
  {t: 'What happens when you press "Extract JSON"',
   flow: ['browser', 'POST /api/jobs', 'validate + save to tmp/uploads/&lt;id&gt;/', '[[http202|202]] + job id', '[[executor|worker thread]] runs extract_pdf', '[[polling|poll]] every 700 ms', 'review beside page', 'download JSON / ZIP'],
   x: `<p>The request returns <b>immediately</b> with 202 Accepted. The slow part (reading PDFs) happens on a background thread, while the page polls <code>GET /api/jobs/{id}</code> to show progress per page.</p>`,
   analogy: 'The same pattern as an async inference endpoint: accept, enqueue, return a job id, and let the client poll for status. It avoids request timeouts on large batches.'},
  {t: 'The gate: validate before trusting',
   code: {src: 'app', find: 'if not 1 <= len(files) <= MAX_FILES', n: 3, off: 0},
   x: `<ul class="keys"><li>1–10 files; a name ending in <code>.pdf</code>, ≤ 200 characters, with no control characters.</li><li>Streamed in 64 KB chunks: it stops at <b>25 MB</b> per file or <b>100 MB</b> per batch ([[http413|413]]) without ever holding the whole batch in memory.</li><li>The first 1 KB must contain <code>%PDF-</code> (a "magic number" check), so a renamed .txt is rejected.</li><li>On any error, the job and its folder are removed, leaving no half-created state.</li></ul>`,
   code2: null},
  {t: 'One worker, one lock',
   code: {src: 'app', find: 'ThreadPoolExecutor(max_workers=1', n: 1},
   x: `<p>Jobs run <b>one at a time</b> on a single thread. PDF parsing is CPU- and memory-heavy, and one worker keeps a laptop responsive and results in order.</p><p>Because the worker and the web requests both touch the <code>JOBS</code> dict, every read and write happens under a re-entrant [[lock]]. A progress callback updates <code>pages_done</code> after each page.</p>`,
   warn: 'Jobs live in memory. Restarting the server forgets them, and start-up deletes old upload folders. That is fine for a local tool, but a shared or production deployment needs a database and a real queue.'},
  {t: 'Partial failure is normal',
   x: `<p>In a batch, each PDF succeeds or fails <b>on its own</b>. The job is "complete" if at least one document succeeded. The ZIP contains <code>01_name.json</code>, <code>02_…</code> plus an <code>errors.json</code> for the failures.</p>`,
   lab: 'jobs',
   task: {id: 'door-partial', text: 'In the lab, run a batch that includes the broken PDF and look at the ZIP contents.', on: 'lab', test: d => d.id === 'jobs' && d.what === 'zip' && d.failed > 0}},
  {t: 'Temporary by design',
   table: [['Limit', 'Value', 'Why'], ['Files per batch', '10', 'keeps a batch reviewable'], ['Per file / batch', '25 MB / 100 MB', 'bounded disk + memory'], ['Pages per PDF', '200', 'bounded runtime'], ['Jobs kept', '12', 'queue full → 429'], ['Retention', '60 min idle', 'uploads are sensitive; cleanup runs on API access'], ['Bind address', '127.0.0.1', 'reachable from this computer only']],
   x2: `<p><b>New batch</b> deletes the finished batch's files at once. Downloaded JSON is yours; the server copy is temporary.</p>`},
  {t: 'Page previews',
   code: {src: 'app', find: 'bitmap = page.render(scale=min(1600', n: 1},
   x: `<p>The review screen shows the real page beside the data. It is rendered on demand with [[pdfium|pypdfium2]] at about 1600 px wide, cached as a PNG in the job folder, and guarded by a lock so two requests don't render the same page twice.</p>`,
   pro: 'pypdfium2 and Pillow are not listed in requirements.txt. They arrive because pdfplumber depends on them. It works, but pinning them explicitly is a cheap reliability fix to mention.'},
 ],
 explain: {newbie: "You upload PDFs, the page says 'got it' immediately, and a helper in the background reads them one by one while the page keeps checking progress. If one file is broken, the others still finish, and the broken one is listed separately.", inter: 'FastAPI endpoint returns 202 with a job id; a single-thread executor runs extract_pdf per document; clients poll GET /api/jobs/{id}. Validation (count, size streamed in 64 KB chunks, %PDF- magic) rejects the whole batch; extraction errors are isolated per document and reported in errors.json.', together: 'The app works like a dry-cleaning counter: you hand over the batch and get a ticket at once (202 + job id), one worker processes the items in order, and you check the ticket for progress. A torn item (a broken PDF) is returned with a note while the rest are cleaned. For Ashok Leyland this means a big batch never times out and one bad file never ruins the others.'},
 keys: ['Upload returns 202 fast; one background worker extracts; the browser polls.', 'Validation: count, name, size (streamed), %PDF- magic; on failure, clean up everything.', 'Per-document failure isolation, with errors.json in the ZIP.', 'Temporary, local, in memory: right for a desktop tool, not yet for a shared service.'],
 say: '"The API accepts the batch and returns 202 at once. A single worker thread extracts each PDF independently, so one corrupt file never sinks the batch; it shows up in errors.json."',
 quiz: [
  {q: 'A user uploads 3 PDFs; the second is password-protected. What do they get?', o: ['An error for the whole batch', 'Two extracted documents, one failed document with a readable error, and a ZIP with errors.json', 'Three empty JSON files'], a: 1,
   why: ['Failures are isolated per document. test_batch_duplicates_and_partial_failure proves it.', 'Correct. The job status is "complete" because at least one document succeeded.', 'The engine raises ExtractionError for unreadable PDFs; it never writes an empty result.']},
  {q: 'Why stream uploads in 64 KB chunks instead of reading each file at once?', o: ['To enforce the 25 MB / 100 MB limits early without holding everything in memory', 'Because FastAPI cannot read whole files', 'To make uploads faster'], a: 0,
   why: ['Correct. It stops as soon as a limit is crossed.', 'It can. Streaming is a choice made for safety.', 'Speed is about the same. The benefit is bounded memory and early rejection.']},
 ]},

/* ================================================================== 4 */
{id: 'cells', n: 4, short: 'Lines → cells', title: 'Lines become cells', level: 'Intermediate',
 goal: 'Explain how find_tables() turns lines into a grid, and how _table_data() records spans, cells and the rows matrix.',
 page: {spec: 't02-01', layers: ['rules', 'cells']},
 beats: [
  {t: 'find_tables(): from lines to a grid',
   page: {layers: ['rules', 'cells'], focus: null},
   x: `<p>[[findtables|find_tables()]] snaps nearby lines together, finds where they cross, and forms rectangles, which are the cells. On this page it finds <b>two tables</b>: the main one (32 grid rows × 6 grid columns) and the small signature footer.</p>`,
   code: {src: 'engine', find: 'tables = [_table_data(t, number, i)', n: 1},
   x2: `<p>Toggle <b>Cells</b> against <b>Ruling lines</b> to see the lines turn into boxes.</p>`},
  {t: 'Why 6 columns when you can see 3?',
   page: {layers: ['cells'], focus: {rows: [0, 1, 2, 3]}},
   x: `<p>Word leaves thin [[spacer|spacer columns]] wherever rows have slightly different borders. The grid is the union of <i>all</i> border positions, so a visible 3-column table becomes 6 grid columns. Row A1.0 in the <code>rows</code> matrix:</p><pre class="mono small">['A1.0', None, 'Details of Vehicle Manufacturer:', '', None, None]</pre><p><code>None</code> = a grid position covered by a neighbouring merged cell. <code>''</code> = a real cell that is empty.</p>`,
   pro: 'This is why the engine never uses "column 2 = description". Column indexes shift from table to table; geometry does not. Hold on to that: it is the reason for value_x (Station 6).'},
  {t: 'Spans: counting grid lines inside a cell',
   code: {src: 'engine', find: 'xs = sorted({round(v, 4)', n: 13, hl: [9, 10]},
   x: `<p>For each real cell, <code>row_span</code> is the number of grid row starts inside its box and <code>column_span</code> the same for columns. A cell with a span above 1 is [[merged]] (violet on the page).</p>`},
  {t: 'Merged rows in the wild',
   page: {spec: 't03-01', layers: ['cells'], focus: {rows: [1, 2, 3, 4]}},
   x: `<p>Table 03, B1.1 "Overall Length": the value <b>4925</b> is one cell stretched over two rows (FSD and HSD), and so is <b>5225</b>. The code "B1.1" and its description span all three rows.</p><p>Visually it is obvious that HSD = 4925. In the data, the HSD row's own positions are <code>None</code>.</p>`,
   task: {id: 'cells-hsd', text: 'Click the <b>HSD</b> row (the third B1.1 row) on the page.', on: 'row', test: d => d.spec === 't03-01' && d.row === 4}},
  {t: 'Two views of one table',
   x: `<p>The JSON keeps both views of every table:</p><table class="t"><tr><th><code>rows</code> matrix</th><th><code>cells</code> list</th></tr><tr><td>easy to scan, one entry per grid position, <code>None</code> where covered</td><td>the truth: one entry per real cell, with row, column, row_span, column_span, text and bbox</td></tr></table><p>The review UI's <b>Tables</b> tab redraws the original layout from <code>cells</code>, merges included.</p>`,
   code: {src: 'engine', find: 'return {"id": f"p{page_number}-t{index}"', n: 3}},
 ],
 explain: {newbie: 'The program finds where the printed lines cross and turns every enclosed rectangle into a box (cell). Some boxes are stretched over several rows, like a merged cell in Excel; the program remembers how far each one stretches.', inter: 'find_tables() snaps edges, intersects them and builds cells; spans are counted from grid lines inside each cell box. Two views are kept: the rows matrix (None for positions covered by a merged cell) and the cells list (one entry per real cell, with spans and bbox).', together: 'From the printed lines the script builds the grid of boxes, and it records merged boxes with their spans instead of pretending the covered spots are empty. Word adds thin extra columns, so the grid can have 6 columns where you see 3, which is why later rules use positions (x numbers), not column numbers. It is like a spreadsheet that remembers which cells were merged, so nobody mistakes a merged cell for missing data.'},
 keys: ['find_tables() builds cells from ruling lines; Word spacers inflate the column count.', 'Never trust column indexes; trust coordinates.', 'Spans come from counting grid lines inside a cell box.', 'rows (with None) is for scanning; cells (with spans) is the truth.'],
 say: '"We reconstruct the grid from the ruling lines and keep both the position matrix and the real cells with spans, so merged cells stay explicit instead of silently becoming blanks."',
 quiz: [
  {q: 'In the rows matrix, what does <code>None</code> mean vs <code>\'\'</code>?', o: ['Both mean the cell is empty', 'None = the position is covered by a merged neighbour; \'\' = a real cell with no text', 'None = parse error'], a: 1,
   why: ['They are different, and mixing them up is the classic merged-cell bug.', 'Correct.', 'There was no error; it is a merged cell.']},
  {q: 'Why does Table 02 have 6 grid columns when it looks like 3?', o: ['pdfplumber adds columns randomly', 'Tiny differences in border positions between rows create narrow spacer columns', 'Hidden columns contain secret data'], a: 1,
   why: ['It is deterministic: the grid is the union of all line positions.', 'Correct. That is why the engine works with x-coordinates, not column indexes.', 'The spacers are empty slivers.']},
 ]},
];
